name: test-docker
on: [push]
jobs:
  test-it:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Set up python
        uses: actions/setup-python@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install docker-compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          legacy: true
      - name: Hand run docker
        run: |
          docker pull maj1/mdb-test-versioned:latest
          docker run -d -p7474:7474 -p7687:7687 --name mdb maj1/mdb-test-versioned
          sleep 20
          docker logs mdb
          curl -X GET http://localhost:7474
      - name: Check out
        uses: actions/checkout@v3
      - name: Install package
        run: poetry install
      - name: Run pytest
        run: poetry run pytest
        
    
